[build]
  # Disable CI mode during install and build so warnings don't fail the build
  command = "CI=false npm ci --legacy-peer-deps && CI=false npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  # Use Node 18 which matches package requirements
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
